# Schema for the configuration files of the Element Embed module.

embed.embed_type_settings.element_embed:
  type: mapping
  label: 'Schema for the Element embed type additions to an embed button entity'
  mapping:
    element_type:
      type: string
      label: 'Element type'

block.settings.element_embed:
  type: block_settings
  label: 'Embeddable render element block settings'
  mapping:
    element_type:
      type: string
      label: Element type
    element_settings:
      type: element.[%parent.element_type].settings
      label: Element settings
