# Schema for the configuration files of the Text Resize module.

text_resize.settings:
  type: config_object
  label: 'Text Resize settings'
  mapping:
    text_resize_scope:
      type: string
      label: 'Text Resizing Scope'
    text_resize_minimum:
      type: integer
      label: 'Minimum font size in pixels'
    text_resize_maximum:
      type: integer
      label: 'Maximum font size in pixels'
    text_resize_reset_button:
      type: boolean
      label: 'Display reset button'
    text_resize_line_height_allow:
      type: boolean
      label: 'Modify line height'
    text_resize_line_height_min:
      type: integer
      label: 'Minimum line height in pixels'
    text_resize_line_height_max:
      type: integer
      label: 'Maximum line height in pixels'
